### ISSUE TITLE
Auto App updater

### ISSUE THREAD

**Issue by ekurutepe** [XCLocalize/XCLocalize-Issues#5]
Update the app at launch time if there is a newer build available.

**Comment by ekurutepe** [comment]
Sparkle is integrated starting from v1.0.3

**Comment by twilightDD** [comment]
May I ask: How do I get the version with the Sparkle Updater as a 1.02 user?

**Comment by ekurutepe** [comment]
@twilightDD it should be available for download on [Gumroad](https://ekurutepe.gumroad.com/l/xclocalize) and I also emailed everybody who purchased an earlier version with the updated binary.
